version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_test_compose
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - "8888:8888"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./work:/home/jovyan/work/
  
  mariaDB:
    image: mariadb
    container_name: cc104.rds.local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cc104rds
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    depends_on:
      - jupyter
 
  dynamoDB:
    image: amazon/dynamodb-local
    container_name: cc104.dynamodb.local
    ports:
      - "8000:8000"
    depends_on:
      - mariaDB

  sqs:
    image: vsouza/sqs-local
#    build:
#      context: ./docker-sqs-local
#      dockerfile: Dockerfile
    container_name: cc104.sqs.local
    ports:
      - "9324:9324"
    volumes:
      - ./config/elasticmq.conf:/etc/elasticmq/elasticmq.conf
    depends_on:
      - dynamoDB

  s3:
    image: gliffy/fake-s3
    container_name: cc104.s3.local
    ports:
      - "4569:4569" #for HTTP
    depends_on:
      - sqs
  
  sns:
    image: s12v/sns
    container_name: cc104.sns.local
    ports:
      - "9911:9911"
    depends_on:
      - sqs
    volumes:
      - ./config/db.json:/etc/sns/db.json
